#create a database called pets
CREATE DATABASE pets;
#creating tables
CREATE TABLE PETSALE (
 ID INTEGER NOT NULL, 
 PET VARCHAR(20),
 SALEPRICE DECIMAL(6,2),
 PROFIT DECIMAL (6,2),
 SALEDATE DATE);
 
 CREATE TABLE pet ( ID INTEGER NOT NULL,
 ANIMAL VARCHAR(20),
 QUANTITY INTEGER);
 
 SELECT * FROM pet;
 
 #inserting values into the tables
 INSERT INTO PETSALE VALUES
 (1, 'Cat', 450.09, 100.47, '2018-05-29'),
 (2, 'Dog', 666.66, 150.76, '2018-06-01'),
 (3, 'Parrot', 50.00, 8.9, '2018-06-04'),
 (4, 'Hamster', 60.60, 12.0, '2018-06-11'),
 (5, 'Goldfish', 48.48, 3.5, '2018-06-14');
 
 SELECT * FROM PETSALE;
 
 INSERT INTO PET VALUES
 (1, 'Cat', 3),
 (2, 'Dog', 4),
 (3, 'Hamster', 2);
 
 SELECT * FROM PET;
 
 #SELECT STATEMENTS
 
 SELECT * FROM PETSALE;
 
 #SELECTING ONLY THE ID AND PROFIT COLUMN
 SELECT ID, PROFIT FROM PETSALE;
 
 SELECT ANIMAL FROM PET;
 
 #TO ADD A NEW COLUMN
 ALTER TABLE PETSALE
 ADD COLUMN QUANTITY INTEGER;
 
 #to input values into the column created
 UPDATE PETSALE SET QUANTITY = 9 WHERE ID = 1;
 UPDATE PETSALE SET QUANTITY = 3 WHERE ID = 2;
 UPDATE PETSALE SET QUANTITY = 2 WHERE ID = 3;
 UPDATE PETSALE SET QUANTITY = 6 WHERE ID = 4;
 UPDATE PETSALE SET QUANTITY = 24 WHERE ID = 5;
 
 SELECT * FROM PETSALE;
 
 #TO DROP A COLUMN
 ALTER TABLE PETSALE
 DROP COLUMN PROFIT;
 
 #TO CHANGE THE DATATYPE
 ALTER TABLE PETSALE
 MODIFY COLUMN PET CHAR(20);
 
 #TO RENAME A COLUMN
 ALTER TABLE PETSALE
 RENAME COLUMN PET TO ANIMAL;
 
 SELECT * FROM PETSALE;
 